# Generated by Django 3.2.13 on 2023-03-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='APILables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('la_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('type', models.CharField(blank=True, max_length=256)),
                ('mask', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='APIClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_id', models.PositiveIntegerField()),
                ('parent', models.PositiveIntegerField(blank=True)),
                ('title', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classificator.apigroups')),
                ('lables', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classificator.apilables')),
            ],
        ),
    ]
