# Generated by Django 3.2.13 on 2023-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificator', '0002_auto_20230320_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiclasses',
            name='groups',
        ),
        migrations.AddField(
            model_name='apiclasses',
            name='groups',
            field=models.ManyToManyField(to='classificator.APIGroups'),
        ),
        migrations.RemoveField(
            model_name='apiclasses',
            name='lables',
        ),
        migrations.AddField(
            model_name='apiclasses',
            name='lables',
            field=models.ManyToManyField(to='classificator.APILables'),
        ),
    ]
