# Generated by Django 3.2.13 on 2023-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificator', '0003_auto_20230320_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclasses',
            name='groups',
            field=models.ManyToManyField(blank=True, to='classificator.APIGroups'),
        ),
        migrations.AlterField(
            model_name='apiclasses',
            name='lables',
            field=models.ManyToManyField(blank=True, to='classificator.APILables'),
        ),
    ]
