# Generated by Django 3.2.13 on 2023-03-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classificator', '0004_auto_20230320_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiclasses',
            name='parent',
        ),
    ]
